@HostAddress = http://localhost:5180
@Token = 00b58062-bd2b-41de-892e-24370b524a20

### Ok request, dont forget to get a fresh token from authorize endpoint

GET {{HostAddress}}/api/vehicle/31873/emissions
Content-Type: application/json
Accept: application/json
Token: {{Token}}

### Ok request

GET {{HostAddress}}/api/vehicle/26425/emissions
Content-Type: application/json
Accept: application/json
Token: {{Token}}

### Test getting not existent vehicle

GET {{HostAddress}}/api/vehicle/999999/emissions
Content-Type: application/json
Accept: application/json
Token: {{Token}}

### Test wrong token

GET {{HostAddress}}/api/vehicle/31873/emissions
Content-Type: application/json
Accept: application/json
Token: qwerty

### Test no token

GET {{HostAddress}}/api/vehicle/31873/emissions
Content-Type: application/json
Accept: application/json