@HostAddress = http://localhost:5180
@Token = bbaffbfc-87a1-4d6f-ac4e-28304e6631fc

### Ok request, dont forget to get a fresh token from authorize endpoint

GET {{HostAddress}}/api/vehicle/31873/emissions
Content-Type: application/json
Accept: application/json
Authorization: {{Token}}

### Ok request

GET {{HostAddress}}/api/vehicle/26425/emissions
Content-Type: application/json
Accept: application/json
Authorization: {{Token}}

### Test getting not existent vehicle

GET {{HostAddress}}/api/vehicle/999999/emissions
Content-Type: application/json
Accept: application/json
Authorization: {{Token}}

### Test wrong token

GET {{HostAddress}}/api/vehicle/31873/emissions
Content-Type: application/json
Accept: application/json
Authorization: qwerty

### Test no token

GET {{HostAddress}}/api/vehicle/31873/emissions
Content-Type: application/json
Accept: application/json